mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todos/',include('todos.urls')),
    path('admin/', admin.site.urls),
]

todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('addtodo/', views.addtodo, name = 'addtodo'),
    path('<int:todo_id>/delete_todo', views.deletetodo, name='deletetodo'),
    path('<int:todo_id>/editform', views.editform, name = 'editform'),
    path('<int:todo_id>/edittodo', views.edittodo, name= 'edittodo'),
]

todos/models.py
from django.db import models

# Create your models here.

class Todo(models.Model):
    content = models.TextField(max_length=250)

    def __str__(self):
        return self.content

todos/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Todo
from django.urls import reverse
# Create your views here.

def index(request):
    todo_list = Todo.objects.all()
    return render(request, 'todos/index.html',{'todo_list':todo_list})

def addtodo(request):
    new_todo = Todo(content = request.POST['content'])
    new_todo.save()
    return HttpResponseRedirect(reverse('todos:index'))

def deletetodo(request, todo_id):
    todo = Todo.objects.get(pk = todo_id)
    todo.delete()
    return HttpResponseRedirect(reverse('todos:index'))

def editform(request, todo_id):
    todo = Todo.objects.get(pk = todo_id)
    return render(request, 'todos/editform.html', {'todo':todo})

def edittodo(request, todo_id):
    todo = Todo.objects.get(pk = todo_id)
    todo.content = request.POST['content']
    todo.save()
    return HttpResponseRedirect(reverse('todos:index'))

todos/templates/todos/editform.html
<h3>Edit...</h3>
<form action="{% url 'todos:edittodo' todo.id %}" method="post">
{% csrf_token %}
    <input type="text" name = 'content' value="{{ todo.content }}">
    <input type="submit", value="submit">
</form>

todos/templates/todos/index.html
{% if todo_list %} 
    <h3>Existing todos are : -</h3>
    <ul>
        {% for todo in todo_list %} 
            <li>{{ todo.content }} &nbsp; <a href="{% url 'todos:deletetodo' todo.id %}">Delete</a> &nbsp; <a href="{% url 'todos:editform' todo.id %}">Edit</a></li>
        {% endfor %}
    </ul>
{% else %} 
    <p>You don't have any todos</p>
{% endif %}

<h3>Create Todos</h3>
<form action="{% url 'todos:addtodo' %}" method="post">
{% csrf_token %}
    <input type="text" name="content">
    <input type="submit" value="submit">
</form>